import React from 'react';
import { styles } from './stylepdf';
import { Page, Text, View, Document, PDFViewer } from '@react-pdf/renderer';

function Pdfview() {
  const MyDocument = (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerText}>Nova Payment</Text>
        </View>

        {/* Payment Details */}
        <View style={styles.detailsContainer}>
          {/* Left side */}
          <View style={styles.column}>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Date:</Text>
              <Text style={styles.value}>12/22/2024</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Voucher No:</Text>
              <Text style={styles.value}>123456789</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Payee:</Text>
              <Text style={styles.value}>John Doe</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Payment Details:</Text>
              <Text style={styles.value}>Consultation services</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Account Code:</Text>
              <Text style={styles.value}>AC-00123</Text>
            </View>
          </View>

          {/* Right side */}
          <View style={styles.column}>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Beneficiary Code:</Text>
              <Text style={styles.value}>BN-45678</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Budget Code:</Text>
              <Text style={styles.value}>BG-78901</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Exchange Rate:</Text>
              <Text style={styles.value}>3,750 UGX/USD</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Amount (Figures):</Text>
              <Text style={styles.value}>1,000,000 UGX</Text>
            </View>
            <View style={styles.detailItem}>
              <Text style={styles.label}>Amount (Words):</Text>
              <Text style={styles.value}>One Million Ugandan Shillings</Text>
            </View>
          </View>
        </View>

        {/* Status and Footer */}
        <View style={styles.detailItem}>
          <Text style={styles.label}>Status:</Text>
          <Text style={styles.value}>Approved</Text>
        </View>
        <View style={styles.detailItem}>
          <Text style={styles.label}>Document Attached:</Text>
          <Text style={styles.value}>Invoice_12345.pdf</Text>
        </View>

        <View style={styles.footer}>
          <Text>Generated by Nova Payment System</Text>
        </View>
      </Page>
    </Document>
  );

  return (
    <div className="w-full h-[750px]">
      <PDFViewer width="100%" height="100%">
        {MyDocument}
      </PDFViewer>
    </div>
  );
}

export default Pdfview;
